### ISSUE TITLE
BUG:  Coarse and key velocity parameters of operators wrongly assigned. 

### ISSUE THREAD

**Issue by hjdeheer** [xerhard/DX7syx-to-XFM2patches#2]
The coarse parameter is assigned to the key velocity parameter. Coarse is always set to 0.

In line 105 in JavaSysEx.java: `DX7Par[15+p*21] = (allBytes[startpos + p*17 + 15] & 0x3E)>>1;`
should be changed into `DX7Par[18+p*21] = (allBytes[startpos + p*17 + 15] & 0x3E)>>1;`

This change should fix it!

**Comment by xerhard** [comment]
Thanx for your hawkeye, corrected the code

**Comment by xerhard** [comment]
compiled too and upoaded new zip file
